config/routes.rb
Rails.application.routes.draw do
  get '/enfermeros/listado/:id', to: "enfermeros#baja", as: "baja"
  get '/pacientes/:id', to: "main#alta", as: "main_alta"
  get 'estadisticas/mostrar'
 
 ## get 'estadisticas/seleccionar', to: "estadisticas#seleccionar", as: "seleccionar"
  get 'enfermeros/listado', to: "enfermeros#listado", as: "listadoenfermero"
  patch 'turno/:id', to: "turnos#turno", as: "turno"  ## para guardar la nota
  patch '/aplicadasinturnoform', to: "comprobante#aplicadasinturnoform", as: "sinturno" 
  patch '/crearturnofiebreamarilla/:id', to: "turnos#crearturnofiebreamarilla", as: "crearturnofiebreamarilla"
  patch '/crearturnogripe/:id', to: "turnos#crearturnogripe", as: "crearturnogripe"
  patch '/crearturnocovid2/:id', to: "turnos#crearturnocovid2", as: "crearturnocovid2"
  patch '/crearturnocovid1/:id', to: "turnos#crearturnocovid1", as: "crearturnocovid1"
  get 'comprobante/index/:id', to: "comprobante#index", as: "comprobante_index"
  get '/crearcomprobante/:id', to: "comprobante#crearcomprobante", as: "crearcomprobante"
  get '/historialdeturnos', to: "turnos#historialdeturnos", as: "historialdeturnos"
   get '/historialdeturnospaciente/:id', to: "turnos#historialdeturnospaciente", as: "historialdeturnospaciente"
   get '/aplicadasinturno', to: "turnos#aplicadasinturno", as: "aplicadasinturno"
  get '/noaplicada/:id', to: "turnos#noaplicada", as: "noaplicada"
  get '/noasistencia/:id', to: "turnos#noasistencia", as: "noasistencia"
  get '/asistencia/:id', to: "turnos#asistencia", as: "asistencia"
  get 'turnos/listado', to: "turnos#listado", as: "ver_lista_turnos"
  get 'vacunatorios/ver_contacto'
  devise_for :users, controllers:{registrations: 'users/registrations' }
  get "/verdatos", to: "main#ver", as:"verdatos"
  get "/verlistadoturnos", to: "main#verlistadoturnos", as:"verlistadoturnos"
  get "/verdetalleturno/:id", to: "main#verdetalleturno", as:"verdetalleturno"
  get "/verhistoria/:id", to: "main#verhistoria", as:"verhistoria"
  get "/covid1", to: "main#turnoscovid1", as:"turnoscovid1"
  get "/covid2", to: "main#turnoscovid2", as:"turnoscovid2"
  get "/fiebreamarilla", to: "main#turnosfiebreamarilla", as:"turnosfiebreamarilla"
  get "/gripe", to: "main#turnosgripe", as:"turnosgripe"
  get "/pacientes", to: "main#pacientes", as:"pacientes"
  get "/obtenerturno/:id" , to: "main#obtenerturno", as:"obtenerturno"
  get "/cancelarturno/:id" , to: "main#cancelarturno", as:"cancelarturno"
  get "/cancelarturnocovid1/:id" , to: "main#cancelarturnocovid1", as:"cancelarturnocovid1"
  get "/cancelarturnocovid2/:id" , to: "main#cancelarturnocovid2", as:"cancelarturnocovid2"
  get "/buscar", to: "main#search", as:"buscar"
  get "/buscarturnos", to: "turnos#searchturnos", as:"searchturnos"
  get "/buscarenfermero", to: "main#searchenfermero", as:"buscarenfermero"
  get "/verdatospaciente/:id", to: "main#verdatospaciente", as:"verdatospaciente"
  get "/verinformacionenfermero/:id", to: "enfermeros#verinformacionenfermero", as:"verinformacionenfermero"
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
   get "/enfermero", to: "main#pantallaenfermero", as:"pantallaenfermero"
   get "/admin", to: "main#pantallaadmin", as:"pantallaadmin"
  get "/home", to: "main#home", as:"home"
  root 'main#home'
end

app/controllers/main_controller.rb
class MainController < ApplicationController
  before_action :authenticate_user!
  def home
  end
 
  ##enfermeros
  def pantallaenfermero
  end
  def pantallaadmin
  end
  def pacientes
  end
  def search
    if params[:search].blank?  
    	redirect_to(pacientes_path, alert: "Por favor ingrese un DNI o Apellido") and return  
    else 
      @parameter = params[:search]
      if @parameter.first.match(/[0-9]/)
        @users = User.all.where("lower(DNI) LIKE :search", search: "%#{@parameter}%")
      else
          @parameter = params[:search].downcase
          @users = User.all.where("lower(apellido) LIKE :search", search: "%#{@parameter}%")
      end
    end
  end
  def searchenfermero
    if params[:search].blank?  
    	redirect_to(listadoenfermero_path, alert: "Por favor ingrese un DNI o Apellido") and return  
    else 
      @parameter = params[:search]
      if @parameter.first.match(/[0-9]/)
        @users = User.all.where("lower(DNI) LIKE :search", search: "%#{@parameter}%")
      else
          @parameter = params[:search].downcase
          @users = User.all.where("lower(apellido) LIKE :search", search: "%#{@parameter}%")
      end
    end
  end
  
  
  def ver
  end
  def verlistadoturnos
  end
  def verdetalleturno
  end
  def turnoscovid1
  end
  def turnoscovid2
  end
  def turnosfiebreamarilla
  end
  def turnosgripe
  end
  def obtenerturno
     @turno = Turno.find(params[:id])
     @turno.user_id = current_user.id
     @turno.save
     
     redirect_to root_path, notice: "Se obtuvo el turno exitosamente"
  end
  def cancelarturno
     @turno = Turno.find(params[:id])
     @turno.delete
     redirect_to verlistadoturnos_path, notice: "El turno fue cancelado exitosamente"
  end
    def cancelarturnocovid1
     @turno = Turno.find(params[:id])
     @turno.user_id = nil
     @turno.save
     redirect_to turnoscovid1_path(current_user), notice: "El turno fue cancelado exitosamente"
  end
  def cancelarturnocovid2
     @turno = Turno.find(params[:id])
     @turno.user_id = nil
     @turno.save
     redirect_to turnoscovid2_path(current_user), notice: "El turno fue cancelado exitosamente"
  end
  def alta
    e = User.find(params[:id])
    e.rol = 2
    e.fechaalta = Date.today
    e.save
    redirect_to "/pacientes"
  end
end

app/helpers/main_helper.rb
module MainHelper
end

app/views/main/home.html.erb
<!DOCTYPE html> 
<html>
<head>
  
  <meta charset="UTF-8">
  <title> Vacunassist </title>
  <% if current_user.rol == 3 %>
      <% controller.redirect_to pantallaadmin_path(current_user) %>
     <% end %>
  <% if ((current_user.historia.attached? == false) and (current_user.rol == 1)) %>
  <meta HTTP-EQUIV="REFRESH" content="3; /verdatos">
  <% end %>
</head>  
<body>	

  <div class="page-header" align="center">
    <h1 style="margin-left:200px;margin-right:200px">
        Bienvenido <%= current_user.name %> a Vacunassist
    </h1>
  </div>
    <div align="left">
      <h3><%= image_tag "logo.png", title: "Logo", class: "logo" ,style: "width:150px" %></h3>
    </div>
    <% if current_user.rol == 1 or current_user.rol == 2 %>
    <div class="container">
      <div class="row">
         <div class="col-sm-4">
               <% @edad = Date.today.year - current_user.nacimiento.year %>
               <% if Date.today.month <= current_user.nacimiento.month %>
                    <% if Date.today.month <= current_user.nacimiento.month %>
                         <% @edad = @edad-1 %>
                    <% end %>
               <% end %> 
              <% if ((current_user.historia.attached? == false) and (current_user.rol == 1)) %>
                <button disabled=true>  <%= link_to "Obtener Turno COVID19 1era dosis"%></button>
                <%else%>

               <% if current_user.covid1 == false and !Turno.where("nombrevacuna = ? and user_id = ?","covid1",current_user.id).exists?%>
             
               <% if current_user.covid1 == false and !Turno.where("nombrevacuna = ? and user_id = ? and aplicada = ? and fecha >= ?","covid1",current_user.id,false,Date.today).exists? %>
                <% controller.redirect_to turnoscovid1_path(current_user), notice: "Tiene que obtener un turno para continuar" %>
               <button style="background-color:yellow">
	              <%= link_to "Obtener Turno COVID19 1era dosis", turnoscovid1_path(current_user), class: 'btn btn-info btn-sm' %>
	                 </button>
	             <% else %>  
	               <button disabled=true>  <%= link_to "Obtener Turno COVID19 1era dosis"%></button>
	               
               <% end %>
               <% end %>
              <%end%>
              
              <% if ((current_user.historia.attached? == false) and (current_user.rol == 1)) %>
                <button disabled=true>  <%= link_to "Obtener Turno COVID19 2da dosis"%></button>
                <%else%>
               <% if current_user.covid2 == false and current_user.covid1 == true and !Turno.where("nombrevacuna = ? and user_id = ?","covid2",current_user.id).exists?%>
        
               <% if current_user.covid2 == false and current_user.covid1 == true and !Turno.where("nombrevacuna = ? and user_id = ? and aplicada = ? and fecha >= ?","covid2",current_user.id,false,Date.today).exists?%>
                <% controller.redirect_to turnoscovid2_path(current_user), notice: "Tiene que obtener un turno para continuar" %>
                  <button style="background-color:yellow">
	           <%= link_to "Obtener Turno COVID19 2da dosis", turnoscovid2_path(current_user), class: 'btn btn-info btn-sm' %>
	           </button>
	           <% else %>  
	               <button disabled=true>  <%= link_to "Obtener Turno COVID19 2da dosis"%></button>
               <% end %>
               <% end %>
              <% end %>

               <% if ((current_user.historia.attached? == false) and (current_user.rol == 1)) %>
                <button disabled=true>  <%= link_to "Obtener Turno Fiebre Amarilla"%></button>
                <%else%>
               <% if current_user.fiebreamarilla == false and @edad<60 and !Turno.where("nombrevacuna = ? and user_id = ?","fiebreamarilla",current_user.id).exists? %>
               <% if current_user.fiebreamarilla == false and @edad<60 and !Turno.where("nombrevacuna = ? and user_id = ? and aplicada = ? and fecha >= ?","fiebreamarilla",current_user.id,false,Date.today).exists? %>
               <button style="background-color:yellow">
	           <%= link_to "Obtener Turno Fiebre Amarilla", turnosfiebreamarilla_path(current_user), class: 'btn btn-info btn-sm' %>
                  </button>
                  <% else %>  
	               <button disabled=true>  <%= link_to "Obtener Turno Fiebre Amarilla"%></button>
               <% end %>
               <% end %>
              <% end %>

              <% if ((current_user.historia.attached? == false) and (current_user.rol == 1)) %>
                <button disabled=true>  <%= link_to "Obtener Turno Gripe"%></button>
                <%else%>
               <% if current_user.gripe == false and !Turno.where("nombrevacuna = ? and user_id = ?","gripe",current_user.id).exists?%>
               <% if current_user.gripe == false and !Turno.where("nombrevacuna = ? and user_id = ? and aplicada = ? and fecha >= ?","gripe",current_user.id,false,Date.today).exists?%>
                  <button style="background-color:yellow">
	           <%= link_to "Obtener Turno Gripe", turnosgripe_path(current_user), class: 'btn btn-info btn-sm' %>
                          </button>
                   <% else %>  
	               <button disabled=true>  <%= link_to "Obtener Turno Gripe"%></button>
               <% end %>
               <% end %>
              <% end %>

        </div>
        <div class="col-sm-4" align="right">
              <h2>
                <% if ((current_user.historia.attached? == false) and (current_user.rol == 1)) %>
                <button disabled=true>  <%= link_to "Ver Datos Personales"%></button>
                <%else%>
               <button style="background-color:yellow">
	           <%= link_to "Ver Datos Personales", verdatos_path(current_user), class: 'btn btn-info btn-sm' %>
                </button>
                <% end %>
                </h2>
                <h2>
                <% if ((current_user.historia.attached? == false) and (current_user.rol == 1)) %>
                <button disabled=true>  <%= link_to "Ver Listado de Turnos"%></button>
                <%else%>
                <button style="background-color:yellow">
	            <%= link_to "Ver Listado de Turnos", verlistadoturnos_path(current_user), class: 'btn btn-info btn-sm' %>
                 </button>
                <% end %>
               </h2>
               <h2>
               <% if ((current_user.historia.attached? == false) and (current_user.rol == 1)) %>
                <button disabled=true>  <%= link_to "Ver Listado de certificados"%></button>
                <%else%>
                <button style="background-color:yellow">
	            <%= link_to "Ver Certificados", comprobante_index_path(current_user.id), class: 'btn btn-info btn-sm' %>
                 </button>
                 <%end%>
               </h2>
              <h2>

                <button style="background-color:yellow">
	            <%= link_to "Cerrar Sesión", destroy_user_session_path, method: :delete %>
                 </button>
               </h2>
             <% if ((current_user.historia.attached? == false) and (current_user.rol == 1)) %>
                <button disabled=true>  <%= link_to "Eliminar mi cuenta"%></button>
                <%else%>
                <button style="background-color:yellow">
	 	     <%= link_to "Eliminar mi cuenta", registration_path(current_user), data: { confirm: "¿Seguro que quieres eliminar tu cuenta?" }, method: :delete %>
                </button>
                <% end %>
                <h2>
              <% if ((current_user.historia.attached? == false) and (current_user.rol == 1)) %>
                <button disabled=true>  <%= link_to "Ver informacion de contacto"%></button>
                <%else%>
               <button style="background-color:yellow">
	           <%= link_to "Ver informacion de contacto", vacunatorios_ver_contacto_path, class: 'btn btn-info btn-sm' %>
                </button>
                <% end %>
                </h2>
                <% if current_user.rol == 2 %>  
                  <h2>  
                  <button style="background-color:yellow">
	            <%= link_to "Pantalla Enfermero", pantallaenfermero_path(current_user), class: 'btn btn-info btn-sm' %>
                  </button>
                  </h2>    
                <% end %>
       </div>
     </div>
  </div>
  <% end %>
</body>

</html>

app/views/main/pacientes.html.erb
<!DOCTYPE html> 
<html>
<head>
<script type="text/javascript" src="Scripts/jquery-2.1.1.min.js"></script>
<script type="text/javascript" src="Scripts/bootstrap.min.js"></script>
</head>
<body>
<h1> Pacientes registrados en Vacunassist </h1> 
<div>
    <p>
    <%= form_tag(buscar_path, method: 'get') do %>
   <div class="input-group">  
    <%= search_field_tag :search, params[:search], placeholder: "Ingrese DNI o Apellido", class: "form-control" %>  
    <div class="input-group-btn">  
      <%= button_tag "Buscar", :class => 'btn btn-info glyphicon glyphicon-search',:dni => nil%>  
    </div>  
  </div>  
  <% end %>
    </p>
    <% User.all.where(rol: "1").order('name, apellido').each do |user| %>
       <p>
         <p>Nombre: <%= user.name%> Apellido: <%= user.apellido %> DNI <%= user.dni %>
              <button style="background-color:yellow">
	          <%= link_to "Ver Información del paciente", verdatospaciente_path(user), class: 'btn btn-info btn-sm' %>
          </button>   

          <% if user.historia.attached? %>
                <button style="background-color:yellow;">
                 <%= link_to "Ver Historia de Vacunación", user.historia, class: 'btn btn-info btn-sm' %>
                </button>
          <% else %>
                <button disabled=true style="background-color:grey;">
                 <%= link_to "Sin Historia", class: 'btn btn-info btn-sm' %>
                </button>

          <% end %>

          <button style="background-color:yellow">
                 <%= link_to "Ver Certificados del Paciente",comprobante_index_path(user.id), class: 'btn btn-info btn-sm' %>
          </button>  
          <button style="background-color:yellow">
	          <%= link_to "Ver Historial de Turnos del paciente", historialdeturnospaciente_path(user), class: 'btn btn-info btn-sm' %>
          </button>
          <% if current_user.rol == 3 %>
          <button style="background-color:yellow">
	          <%= link_to "Alta de enfermero", main_alta_path(user.id), class: 'btn btn-info btn-sm' %>
          </button>   
          <% end %>
       </p>
    <% end %> 
            


<%= link_to "Atrás", pantallaenfermero_path %>
   

</div>

</body>
</html>

app/views/main/pantallaadmin.html.erb
<!DOCTYPE html> 
<html>
<head>
<script type="text/javascript" src="Scripts/jquery-2.1.1.min.js"></script>
<script type="text/javascript" src="Scripts/bootstrap.min.js"></script>
</head>
<body>
<h1> Administrador Vacunassist </h1> 
<div>
    <p>
    <button style="background-color:yellow">
      <%= link_to "Ver Lista de Pacientes", pacientes_path(current_user), class: 'btn btn-info btn-sm' %>
    </button>
    </p>
    <p>
    <button style="background-color:yellow">
      <%= link_to "Ver Lista de Turnos Diarios", ver_lista_turnos_path(current_user), class: 'btn btn-info btn-sm' %>
    </button>
    </p>
    <p>
    <button style="background-color:yellow">
      <%= link_to "Ver Historial de Turnos", historialdeturnos_path(current_user), class: 'btn btn-info btn-sm' %>
    </button>
    </p>
     <p>
    <button style="background-color:yellow">
      <%= link_to "Ver Lista de Enfermeros", listadoenfermero_path(current_user), class: 'btn btn-info btn-sm' %>
    </button>
    </p>
    <p>
    <button style="background-color:yellow">
      <%= link_to "Ver Estadisticas",estadisticas_mostrar_path, class: 'btn btn-info btn-sm' %>
    </button>
    </p>
    <p>
    <button style="background-color:yellow">
	 <%= link_to "Cerrar Sesión", destroy_user_session_path, method: :delete %>
    </button>
    </p>
<%= link_to "Atrás", home_path %>
   

</div>

</body>
</html>

app/views/main/pantallaenfermero.html.erb
<!DOCTYPE html> 
<html>
<head>
<script type="text/javascript" src="Scripts/jquery-2.1.1.min.js"></script>
<script type="text/javascript" src="Scripts/bootstrap.min.js"></script>
</head>
<body>
<h1> Enfermero de Vacunassist </h1> 
<div>
   <% if current_user.rol == 3 %>
      <% controller.redirect_to pantallaadmin_path(current_user) %>
     <% end %>
    <p>
    <button style="background-color:yellow">
      <%= link_to "Pantalla Paciente", home_path(current_user), class: 'btn btn-info btn-sm' %>
    </button>
    </p>
    <p>
    <button style="background-color:yellow">
      <%= link_to "Ver Lista de Pacientes", pacientes_path(current_user), class: 'btn btn-info btn-sm' %>
    </button>
    </p>
    <p>
    <button style="background-color:yellow">
      <%= link_to "Ver Lista de Turnos Diarios", ver_lista_turnos_path(current_user), class: 'btn btn-info btn-sm' %>
    </button>
    </p>
    <p>
    <button style="background-color:yellow">
      <%= link_to "Ver Historial de Turnos", historialdeturnos_path(current_user), class: 'btn btn-info btn-sm' %>
    </button>
    </p>
<%= link_to "Atrás", home_path %>
   

</div>

</body>
</html>

app/views/main/search.html.erb
<!DOCTYPE html> 
<html>
<body>
<h1>Resultados de la Búsqueda</h1> 
   <% if not @users.any? %>
      <p> No hay coincidencias </p>
   <% end %> 
   <% @users.all.where(rol: "1").or(@users.where(rol: "2")).order('name, apellido').each do |user| %>
       <p>
         <p>Nombre: <%= user.name %> Apellido: <%= user.apellido %> DNI <%= user.dni %>
              <button style="background-color:yellow">
	          <%= link_to "Ver Información del paciente", verdatospaciente_path(user), class: 'btn btn-info btn-sm' %>
          </button>   
          <% if user.historia.attached? %>
                <button style="background-color:yellow;">
                 <%= link_to "Ver Historia de Vacunación", user.historia, class: 'btn btn-info btn-sm' %>
                </button>
          <% else %>
                <button disabled=true style="background-color:grey;">
                 <%= link_to "Sin Historia", class: 'btn btn-info btn-sm' %>
                </button>

          <% end %>
           <button style="background-color:yellow">
                 <%= link_to "Ver Certificados del Paciente",comprobante_index_path(user.id), class: 'btn btn-info btn-sm' %>
          </button>  
          <button style="background-color:yellow">
	          <%= link_to "Ver Historial de Turnos del paciente", historialdeturnospaciente_path(user), class: 'btn btn-info btn-sm' %>
          </button>     
       </p>
    <% end %> 


    
<%= link_to "Atrás", pacientes_path(current_user) %>
   

</div>

</body>
</html>

app/views/main/searchenfermero.html.erb
<!DOCTYPE html> 
<html>
<body>
<h1>Resultados de la Búsqueda</h1> 
   <% if not @users.any? %>
      <p> No hay coincidencias </p>
   <% end %> 
   <% @users.all.where(rol: "2").order('name, apellido').each do |user| %>
       <p>
         <p>Nombre: <%= user.name %> Apellido: <%= user.apellido %> DNI <%= user.dni %>
         <button style="background-color:yellow">
                        <%= link_to "Baja", baja_path(user.id), class: "btn btn-success" %>
        </button>
        <button style="background-color:yellow">
              <%= link_to "Ver Información Enfermero", verinformacionenfermero_path(user.id), class: "btn btn-success" %>
         </button>
                         
       </p>
    <% end %> 


    
<%= link_to "Atrás", listadoenfermero_path(current_user) %>
   

</div>

</body>
</html>

app/views/main/turnoscovid1.html.erb
<!DOCTYPE html> 
<html>
<body>
<h1> Primera dosis COVID-19 </h1> 
<div>
   <h3> Por favor complete todos los campos </h3> 
    <%= form_with url: "/crearturnocovid1/:id", method: :patch do |f| %>
               <div>
                  <%= f.label :vacunatorio %>
                  <%= f.number_field :vacunatorio, required: true , min: 1, max: 3%> 
                  <%= f.label :hora %>
                  <%= f.time_field :hora, required: true, min: "08:00", max: "20:00", step: 900 %> 
                  <%= f.label :fecha %>
                  <%= f.date_field :fecha, required: true%>  
                  <%= f.submit "Obtener Turno"%>
               </div>
                              
                       <% end %>
   
    
<%= link_to "Atrás", home_path(current_user) %>
   

</div>

</body>
</html>

app/views/main/turnoscovid2.html.erb
<!DOCTYPE html> 
<html>
<body>
<h1> Segunda dosis COVID-19 </h1> 
<div>
   <h3> Por favor complete todos los campos </h3> 
    <%= form_with url: "/crearturnocovid2/:id", method: :patch do |f| %>
               <div>
                  <%= f.label :vacunatorio %>
                  <%= f.number_field :vacunatorio, required: true , min: 1, max: 3%> 
                  <%= f.label :hora %>
                  <%= f.time_field :hora, required: true, min: "08:00", max: "20:00", step: 900 %> 
                  <%= f.label :fecha %>
                  <%= f.date_field :fecha, required: true%>  
                  <%= f.submit "Obtener Turno"%>
               </div>
                              
                       <% end %>
   
    
<%= link_to "Atrás", home_path(current_user) %>
   

</div>

</body>
</html>

app/views/main/turnosfiebreamarilla.html.erb
<!DOCTYPE html> 
<html>
<body>
<h1> Fiebre Amarilla </h1> 
<div>
   <h3> Por favor complete todos los campos </h3> 
    <%= form_with url: "/crearturnofiebreamarilla/:id", method: :patch do |f| %>
               <div>
                  <%= f.label :vacunatorio %>
                  <%= f.number_field :vacunatorio, required: true , min: 1, max: 3%> 
                  <%= f.label :hora %>
                  <%= f.time_field :hora, required: true, min: "08:00", max: "20:00", step: 900 %> 
                  <%= f.label :fecha %>
                  <%= f.date_field :fecha, required: true%>  
                  <%= f.submit "Obtener Turno"%>
               </div>
                              
                       <% end %>
   
    
<%= link_to "Atrás", home_path(current_user) %>
   

</div>

</body>
</html>

app/views/main/turnosgripe.html.erb
<!DOCTYPE html> 
<html>
<body>
<h1> Gripe </h1> 
<div>
   <h3> Por favor complete todos los campos </h3> 
    <%= form_with url: "/crearturnogripe/:id", method: :patch do |f| %>
               <div>
                  <%= f.label :vacunatorio %>
                  <%= f.number_field :vacunatorio, required: true , min: 1, max: 3%> 
                  <%= f.label :hora %>
                  <%= f.time_field :hora, required: true, min: "08:00", max: "20:00", step: 900 %> 
                  <%= f.label :fecha %>
                  <%= f.date_field :fecha, required: true%>  
                  <%= f.submit "Obtener Turno"%>
               </div>
                              
                       <% end %>
   
    
<%= link_to "Atrás", home_path(current_user) %>
   

</div>

</body>
</html>

app/views/main/verdatospaciente.html.erb
<!DOCTYPE html> 
<html>
<body>
<h1>Datos del Paciente </h1> 
<div>
    <% u = User.find(params[:id]) %>
    <div>
      <span id="Nombre">Nombre</span>
      <input readonly type="text"  value= "<%=u.name %>" name="Nombre" placeholder="Nombre" required>
    </div>

    <div>
      <span id="Apellido">Apellido</span>
      <input readonly type="text"  value= "<%= u.apellido %>" name="Apellido" placeholder="Apellido" required>
    </div>
    
    <div>
      <span id="DNI">DNI</span>
      <input readonly type="text"  value= "<%= u.dni %>" name="DNI" placeholder="DNI" required>
    </div>
    
     <div>
	<span id="Mail">Mail</span>
      <input readonly type="email"  value= "<%= u.email %>" name="Mail" placeholder="Mail" required>
    </div>
    
    <div>
      <span id="Apellido">Dirección</span>
      <input readonly type="text"  value= "<%= u.direccion %>" name="Direccion" placeholder="Dirección" required>
    </div>
    
    <div>
	<span id="Fecha de nacimiento">Fecha de Nacimiento</span>
      <input readonly type="date"  value= "<%= u.nacimiento %>" name="Nacimieno" placeholder="Fecha de nacimiento" required>
    </div>

    

    
<%= link_to "Atrás", pantallaenfermero_path(current_user) %>
   

</div>

</body>
</html>

app/views/main/verhistoria.html.erb
<!DOCTYPE html> 
<html>
<body>
<h2> Mi Historia de Vacunación </h2> 
<div>

<%= link_to "Atrás", verdatos_path(current_user) %>

<figure class="image is-64x64">
  <%= image_tag(url_for(current_user.historia)) %>
</figure>


</div>

</body>
</html>