config/routes.rb
Rails.application.routes.draw do
  get '/enfermeros/listado/:id', to: "enfermeros#baja", as: "baja"
  get '/pacientes/:id', to: "main#alta", as: "main_alta"
  get 'estadisticas/mostrar'
 
 ## get 'estadisticas/seleccionar', to: "estadisticas#seleccionar", as: "seleccionar"
  get 'enfermeros/listado', to: "enfermeros#listado", as: "listadoenfermero"
  patch 'turno/:id', to: "turnos#turno", as: "turno"  ## para guardar la nota
  patch '/aplicadasinturnoform', to: "comprobante#aplicadasinturnoform", as: "sinturno" 
  patch '/crearturnofiebreamarilla/:id', to: "turnos#crearturnofiebreamarilla", as: "crearturnofiebreamarilla"
  patch '/crearturnogripe/:id', to: "turnos#crearturnogripe", as: "crearturnogripe"
  patch '/crearturnocovid2/:id', to: "turnos#crearturnocovid2", as: "crearturnocovid2"
  patch '/crearturnocovid1/:id', to: "turnos#crearturnocovid1", as: "crearturnocovid1"
  get 'comprobante/index/:id', to: "comprobante#index", as: "comprobante_index"
  get '/crearcomprobante/:id', to: "comprobante#crearcomprobante", as: "crearcomprobante"
  get '/historialdeturnos', to: "turnos#historialdeturnos", as: "historialdeturnos"
   get '/historialdeturnospaciente/:id', to: "turnos#historialdeturnospaciente", as: "historialdeturnospaciente"
   get '/aplicadasinturno', to: "turnos#aplicadasinturno", as: "aplicadasinturno"
  get '/noaplicada/:id', to: "turnos#noaplicada", as: "noaplicada"
  get '/noasistencia/:id', to: "turnos#noasistencia", as: "noasistencia"
  get '/asistencia/:id', to: "turnos#asistencia", as: "asistencia"
  get 'turnos/listado', to: "turnos#listado", as: "ver_lista_turnos"
  get 'vacunatorios/ver_contacto'
  devise_for :users, controllers:{registrations: 'users/registrations' }
  get "/verdatos", to: "main#ver", as:"verdatos"
  get "/verlistadoturnos", to: "main#verlistadoturnos", as:"verlistadoturnos"
  get "/verdetalleturno/:id", to: "main#verdetalleturno", as:"verdetalleturno"
  get "/verhistoria/:id", to: "main#verhistoria", as:"verhistoria"
  get "/covid1", to: "main#turnoscovid1", as:"turnoscovid1"
  get "/covid2", to: "main#turnoscovid2", as:"turnoscovid2"
  get "/fiebreamarilla", to: "main#turnosfiebreamarilla", as:"turnosfiebreamarilla"
  get "/gripe", to: "main#turnosgripe", as:"turnosgripe"
  get "/pacientes", to: "main#pacientes", as:"pacientes"
  get "/obtenerturno/:id" , to: "main#obtenerturno", as:"obtenerturno"
  get "/cancelarturno/:id" , to: "main#cancelarturno", as:"cancelarturno"
  get "/cancelarturnocovid1/:id" , to: "main#cancelarturnocovid1", as:"cancelarturnocovid1"
  get "/cancelarturnocovid2/:id" , to: "main#cancelarturnocovid2", as:"cancelarturnocovid2"
  get "/buscar", to: "main#search", as:"buscar"
  get "/buscarturnos", to: "turnos#searchturnos", as:"searchturnos"
  get "/buscarenfermero", to: "main#searchenfermero", as:"buscarenfermero"
  get "/verdatospaciente/:id", to: "main#verdatospaciente", as:"verdatospaciente"
  get "/verinformacionenfermero/:id", to: "enfermeros#verinformacionenfermero", as:"verinformacionenfermero"
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
   get "/enfermero", to: "main#pantallaenfermero", as:"pantallaenfermero"
   get "/admin", to: "main#pantallaadmin", as:"pantallaadmin"
  get "/home", to: "main#home", as:"home"
  root 'main#home'
end

app/controllers/enfermeros_controller.rb
class EnfermerosController < ApplicationController
  def baja
    e = User.find(params[:id])
    e.rol = 1
    e.fechaalta = nil
    e.save
    redirect_to "/enfermeros/listado"
  end
  def listado
    @e = User.all.where(rol: 2)
  end
  def verinformacionenfermero
  end
end

app/helpers/enfermeros_helper.rb
module EnfermerosHelper
end

app/views/enfermeros/listado.html.erb
<!DOCTYPE html> 
<html>
<h1>Lista de enfermeros</h1>
<% if user_signed_in? and current_user.rol == 3 %>
   <p>
      <%= form_tag(buscarenfermero_path, method: 'get') do %>
   <div class="input-group">  
    <%= search_field_tag :search, params[:search], placeholder: "Ingrese DNI o Apellido", class: "form-control" %>  
    <div class="input-group-btn">  
      <%= button_tag "Buscar", :class => 'btn btn-info glyphicon glyphicon-search',:dni => nil%>  
    </div>  
  </div>  
  <% end %>
    </p>
    <table class = "table">
        <% if not @e.any?%>
            No hay enfermeros en este vacunatorio.
      
        <% else %>
            <th>Nombre Apellido</th>
            <th>DNI</th>
            <tbody>
                <% @e.each do |e| %>
                    <tr>
                        <td><%= e.name %> <%= e.apellido %></td>
                        <td><%= e.dni %></td>
                        <td>
                        <button style="background-color:yellow">
                        <%= link_to "Baja", baja_path(e.id), class: "btn btn-success" %>
                         </button>
                        </td>
                        <td>
                        <button style="background-color:yellow">
                        <%= link_to "Ver Información Enfermero", verinformacionenfermero_path(e.id), class: "btn btn-success" %>
                         </button>
                        </td>
                    </tr>
                <% end %>
            </tbody>
            <% end %>
    </table>
<% else %>
    Acceso denegado.
<% end %>
<%= link_to "Atrás", pantallaadmin_path(current_user) %>
</html>

app/views/enfermeros/verinformacionenfermero.html.erb
<!DOCTYPE html> 
<html>
<body>
<h1>Datos del Enfermero </h1> 
<div>
    <% u = User.find(params[:id]) %>
    <div>
      <span id="Nombre">Nombre</span>
      <input readonly type="text"  value= "<%=u.name %>" name="Nombre" placeholder="Nombre" required>
    </div>

    <div>
      <span id="Apellido">Apellido</span>
      <input readonly type="text"  value= "<%= u.apellido %>" name="Apellido" placeholder="Apellido" required>
    </div>
    
    <div>
      <span id="DNI">DNI</span>
      <input readonly type="text"  value= "<%= u.dni %>" name="DNI" placeholder="DNI" required>
    </div>
    
     <div>
	<span id="Mail">Mail</span>
      <input readonly type="email"  value= "<%= u.email %>" name="Mail" placeholder="Mail" required>
    </div>
    
    <div>
      <span id="Apellido">Dirección</span>
      <input readonly type="text"  value= "<%= u.direccion %>" name="Direccion" placeholder="Dirección" required>
    </div>
    
    <div>
	<span id="Fecha de nacimiento">Fecha de Nacimiento</span>
      <input readonly type="date"  value= "<%= u.nacimiento %>" name="Nacimiento" placeholder="Fecha de nacimiento" required>
    </div>
    
    <div>
    <span id="Fecha de Alta">Fecha de Alta</span>
      <input readonly type="date"  value= "<%= u.fechaalta %>" name="Alta" placeholder="Alta" required>
    </div>
    
    

    
<%= link_to "Atrás", pantallaadmin_path(current_user) %>
   

</div>

</body>
</html>