config/routes.rb
Rails.application.routes.draw do
  get '/enfermeros/listado/:id', to: "enfermeros#baja", as: "baja"
  get '/pacientes/:id', to: "main#alta", as: "main_alta"
  get 'estadisticas/mostrar'
 
 ## get 'estadisticas/seleccionar', to: "estadisticas#seleccionar", as: "seleccionar"
  get 'enfermeros/listado', to: "enfermeros#listado", as: "listadoenfermero"
  patch 'turno/:id', to: "turnos#turno", as: "turno"  ## para guardar la nota
  patch '/aplicadasinturnoform', to: "comprobante#aplicadasinturnoform", as: "sinturno" 
  patch '/crearturnofiebreamarilla/:id', to: "turnos#crearturnofiebreamarilla", as: "crearturnofiebreamarilla"
  patch '/crearturnogripe/:id', to: "turnos#crearturnogripe", as: "crearturnogripe"
  patch '/crearturnocovid2/:id', to: "turnos#crearturnocovid2", as: "crearturnocovid2"
  patch '/crearturnocovid1/:id', to: "turnos#crearturnocovid1", as: "crearturnocovid1"
  get 'comprobante/index/:id', to: "comprobante#index", as: "comprobante_index"
  get '/crearcomprobante/:id', to: "comprobante#crearcomprobante", as: "crearcomprobante"
  get '/historialdeturnos', to: "turnos#historialdeturnos", as: "historialdeturnos"
   get '/historialdeturnospaciente/:id', to: "turnos#historialdeturnospaciente", as: "historialdeturnospaciente"
   get '/aplicadasinturno', to: "turnos#aplicadasinturno", as: "aplicadasinturno"
  get '/noaplicada/:id', to: "turnos#noaplicada", as: "noaplicada"
  get '/noasistencia/:id', to: "turnos#noasistencia", as: "noasistencia"
  get '/asistencia/:id', to: "turnos#asistencia", as: "asistencia"
  get 'turnos/listado', to: "turnos#listado", as: "ver_lista_turnos"
  get 'vacunatorios/ver_contacto'
  devise_for :users, controllers:{registrations: 'users/registrations' }
  get "/verdatos", to: "main#ver", as:"verdatos"
  get "/verlistadoturnos", to: "main#verlistadoturnos", as:"verlistadoturnos"
  get "/verdetalleturno/:id", to: "main#verdetalleturno", as:"verdetalleturno"
  get "/verhistoria/:id", to: "main#verhistoria", as:"verhistoria"
  get "/covid1", to: "main#turnoscovid1", as:"turnoscovid1"
  get "/covid2", to: "main#turnoscovid2", as:"turnoscovid2"
  get "/fiebreamarilla", to: "main#turnosfiebreamarilla", as:"turnosfiebreamarilla"
  get "/gripe", to: "main#turnosgripe", as:"turnosgripe"
  get "/pacientes", to: "main#pacientes", as:"pacientes"
  get "/obtenerturno/:id" , to: "main#obtenerturno", as:"obtenerturno"
  get "/cancelarturno/:id" , to: "main#cancelarturno", as:"cancelarturno"
  get "/cancelarturnocovid1/:id" , to: "main#cancelarturnocovid1", as:"cancelarturnocovid1"
  get "/cancelarturnocovid2/:id" , to: "main#cancelarturnocovid2", as:"cancelarturnocovid2"
  get "/buscar", to: "main#search", as:"buscar"
  get "/buscarturnos", to: "turnos#searchturnos", as:"searchturnos"
  get "/buscarenfermero", to: "main#searchenfermero", as:"buscarenfermero"
  get "/verdatospaciente/:id", to: "main#verdatospaciente", as:"verdatospaciente"
  get "/verinformacionenfermero/:id", to: "enfermeros#verinformacionenfermero", as:"verinformacionenfermero"
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
   get "/enfermero", to: "main#pantallaenfermero", as:"pantallaenfermero"
   get "/admin", to: "main#pantallaadmin", as:"pantallaadmin"
  get "/home", to: "main#home", as:"home"
  root 'main#home'
end

app/models/turno.rb
class Turno < ApplicationRecord 
   has_one :user
   belongs_to :vacunatorio
end

app/controllers/turnos_controller.rb
class TurnosController < ApplicationController
    def listado
       ## @t = Turno.all.where(["fecha = ? and user_id != ?", Date.today, "nil"])
        @t = Turno.all.where(fecha: Date.today).where.not(user_id: nil)
       
    end
    def noaplicada
    redirect_to ver_lista_turnos_path(current_user), notice: "Se marcó vacuna no aplicada"
        @turno = Turno.find(params[:id])
        @turno.aplicada = false
        @turno.save
    end
    def asistencia
    redirect_to ver_lista_turnos_path(current_user), notice: "Se marcó asistencia al turno"
        @turno = Turno.find(params[:id])
        @turno.asistencia = true
        @turno.save
    end
    def noasistencia
    redirect_to ver_lista_turnos_path(current_user), notice: "Se marcó no asistencia al turno"
    	 @turno = Turno.find(params[:id])
    	 @turno.asistencia = false
    	 @turno.save
    end 
    def turno ## para la nota
      redirect_to ver_lista_turnos_path(current_user), notice: "Se agregó la nota con éxito"
      @t = Turno.find(params[:id])
      @texto = params[:turno][:texto]
      @t.texto = @texto
      @t.save
    
    end
    def crearturnocovid1
      redirect_to home_path(current_user), notice: "Se obtuvo el turno correctamente"
      @fecha = params[:fecha]
      @id = current_user.id
      @t = Turno.create(nombrevacuna: "covid1", fecha: params[:fecha], hora: params[:hora], user_id: current_user.id, vacunatorio_id: params[:vacunatorio])
      @dias = (Date.today...@t.fecha).count
      if @dias <= 4
        UserMailer.with(usuario: current_user, fecha: @t.fecha).turno_prox.deliver_later
      else
        UserMailer.with(usuario: current_user, fecha: @t.fecha).turno_prox.deliver_later(wait_until: (@dias).days.from_now)
      end
    end
    def crearturnocovid1
      redirect_to home_path(current_user), notice: "Se obtuvo el turno correctamente"
      @fecha = params[:fecha]
      @id = current_user.id
      @t = Turno.create(nombrevacuna: "covid1", fecha: params[:fecha], hora: params[:hora], user_id: current_user.id, vacunatorio_id: params[:vacunatorio], asistencia: false, aplicada: false)
      @dias = (Date.today...@t.fecha).count
      if @dias <= 4
        UserMailer.with(usuario: current_user, fecha: @t.fecha).turno_prox.deliver_later
      else
        UserMailer.with(usuario: current_user, fecha: @t.fecha).turno_prox.deliver_later(wait_until: (@dias).days.from_now)
      end
    end
    def crearturnocovid2
      redirect_to home_path(current_user), notice: "Se obtuvo el turno correctamente"
      @fecha = params[:fecha]
      @id = current_user.id
      @t = Turno.create(nombrevacuna: "covid2", fecha: params[:fecha], hora: params[:hora], user_id: current_user.id, vacunatorio_id: params[:vacunatorio], asistencia: false, aplicada: false)
      @dias = (Date.today...@t.fecha).count
      if @dias <= 4
        UserMailer.with(usuario: current_user, fecha: @t.fecha).turno_prox.deliver_later
      else
        UserMailer.with(usuario: current_user, fecha: @t.fecha).turno_prox.deliver_later(wait_until: (@dias).days.from_now)
      end
    end
    def crearturnogripe
      redirect_to home_path(current_user), notice: "Se obtuvo el turno correctamente"
      @fecha = params[:fecha]
      @id = current_user.id
      @t = Turno.create(nombrevacuna: "gripe", fecha: params[:fecha], hora: params[:hora], user_id: current_user.id, vacunatorio_id: params[:vacunatorio], asistencia: false, aplicada: false)
      @dias = (Date.today...@t.fecha).count
      if @dias <= 4
        UserMailer.with(usuario: current_user, fecha: @t.fecha).turno_prox.deliver_later
      else
        UserMailer.with(usuario: current_user, fecha: @t.fecha).turno_prox.deliver_later(wait_until: (@dias).days.from_now)
      end
    end
    def crearturnofiebreamarilla
      redirect_to home_path(current_user), notice: "Se obtuvo el turno correctamente"
      @fecha = params[:fecha]
      @id = current_user.id
      @t = Turno.create(nombrevacuna: "fiebreamarilla", fecha: params[:fecha], hora: params[:hora], user_id: current_user.id, vacunatorio_id: params[:vacunatorio], asistencia: false, aplicada: false)
      @dias = (Date.today...@t.fecha).count
      if @dias <= 4
        UserMailer.with(usuario: current_user, fecha: @t.fecha).turno_prox.deliver_later
      else
        UserMailer.with(usuario: current_user, fecha: @t.fecha).turno_prox.deliver_later(wait_until: (@dias).days.from_now)
      end
    end
    def historialdeturnos
    end
    def hisotialdeturnospaciente
    end
    def aplicadasinturno
    end
    def searchturnos
       @fechainicio= params[:fechainicio]
         @fechafin= params[:fechafin]
         @covid1= params[:covid1]
         @covid2= params[:covid2]
        if params[:fechainicio].blank? or params[:fechafin].blank?
    	  redirect_to(historialdeturnos_path, alert: "Por favor ingrese una fecha de inicio y fin") and return  
       else 
         @fechainicio= params[:fechainicio]
         @fechafin= params[:fechafin]
         @covid1= params[:covid1]
         @covid2= params[:covid2]
         @fiebreamarilla= params[:fiebreamarilla]
         @gripe= params[:gripe]
         if 
             @turnos = Turno.all.where("fecha >= ? and fecha <= ? and user_id != ?", @fechainicio, @fechafin, "nil")
          end
        end
    end
end

app/views/turnos/aplicadasinturno.html.erb
<!DOCTYPE html> 
<html>
<body>
<h1> Marcar Vacuna Aplicada sin Turno </h1> 
<div>
   <h3> Por favor complete todos los campos </h3> 
    <%= form_with url: "/aplicadasinturnoform", method: :patch do |f| %>
               <div>
               <p>
                  <%= f.label :DNI, "DNI" %>
                  <%= f.number_field :dni, required: true , min: 1%>
               </p> 
               <p>
                  <%= f.label :vacunatorio %>
                  <%= f.number_field :vacunatorio, required: true , min: 1, max: 3%> 
               </p> 
               <div class="field", required="true">
     			<%= f.label :covid1, "Primera dosis COVID19" %>
    		       <%= f.check_box :covid1 %>
    		       <%= f.label :covid2, "Segunda dosis COVID19" %>
    		       <%= f.check_box :covid2 %>
    		       <%= f.label :gripe, "Fiebre Amarilla" %>
    		       <%= f.check_box :fiebreamarilla %>
    		       <%= f.label :gripe, "Gripe" %>
    		       <%= f.check_box :gripe %>
               </div>
                  <%= f.submit "Marcar Vacuna Aplicada"%>
               </div>
                              
                       <% end %>
   
    
<%= link_to "Atrás", ver_lista_turnos_path(current_user) %>
   

</div>

</body>
</html>

app/views/turnos/historialdeturnos.html.erb
<!DOCTYPE html> 
<html>
<head>
<script type="text/javascript" src="Scripts/jquery-2.1.1.min.js"></script>
<script type="text/javascript" src="Scripts/bootstrap.min.js"></script>
</head>
<body>
<h1> Historial de Turnos </h1> 
<div>
   <p>
      <%= form_tag(searchturnos_path, method: 'get') do %>
   <div class="input-group"> 
     <p>
      Turnos desde:
      <%= date_field_tag :fechainicio, params[:fechainicio], class: "form-control" %>
      </p>
      <p> 
      Hasta:
      <%= date_field_tag :fechafin, params[:fechafin], class: "form-control" %>
      </p> 
    <div class="input-group-btn">  
      <%= button_tag "Buscar", :class => 'btn btn-info glyphicon glyphicon-search',:dni => nil%>  
    </div>  
  </div>  
  <% end %>
    </p>
        <h3> Turnos pasados </h3>
           <% Turno.all.where("fecha < ?", Date.today).where("user_id != ?", "nil").order('fecha, hora').each do |turno|%>
              <p>
              <% @id = turno.user_id %>
              <% if turno.nombrevacuna == "covid1" %>
                  Turno Primera dosis COVID-19 de <%= User.find(@id).name %> <%=User.find(@id).apellido %> Fecha:<%= turno.fecha.day %> / <%= turno.fecha.month %> /  <%= turno.fecha.year %>
            <% end %>
            <% if turno.nombrevacuna == "covid2" %>
                  Turno Segunda dosis COVID-19 de <%= User.find(@id).name %> <%=User.find(@id).apellido %> Fecha:<%= turno.fecha.day %> / <%= turno.fecha.month %> /  <%= turno.fecha.year %>
            <% end %>
            <% if turno.nombrevacuna == "fiebreamarilla" %>
            	  Turno Fiebre Amarilla de <%= User.find(@id).name %> <%=User.find(@id).apellido %> Fecha:<%= turno.fecha.day %> / <%= turno.fecha.month %> /  <%= turno.fecha.year %>
            <% end %>
            <% if turno.nombrevacuna == "gripe" %>
                  Turno Gripe de <%= User.find(@id).name %> <%=User.find(@id).apellido %> Fecha:<%= turno.fecha.day %> / <%= turno.fecha.month %> /  <%= turno.fecha.year %>
            <% end %> 
               <button style="background-color:yellow">
	            <%= link_to "Ver detalles del Turno del Paciente",verdetalleturno_path(turno), class: 'btn btn-info btn-sm' %>
               </button>              
              </p>
           <% end %>
           <h3> Turnos del dia </h3>
            <button style="background-color:yellow">
              <%= link_to "Ver Lista de Turnos Diarios", ver_lista_turnos_path(current_user), class: 'btn btn-info btn-sm' %>
              </button> 
             <% Turno.all.where("fecha = ?", Date.today).where("user_id != ?", "nil").order('fecha, hora').each do |turno|%>
              <p>
              <% @id = turno.user_id %>
              <% if turno.nombrevacuna == "covid1" %>
                  Turno Primera dosis COVID-19 de <%= User.find(@id).name %> <%=User.find(@id).apellido %> Fecha:<%= turno.fecha.day %> / <%= turno.fecha.month %> /  <%= turno.fecha.year %>
            <% end %>
            <% if turno.nombrevacuna == "covid2" %>
                  Turno Segunda dosis COVID-19 de <%= User.find(@id).name %> <%=User.find(@id).apellido %> Fecha:<%= turno.fecha.day %> / <%= turno.fecha.month %> /  <%= turno.fecha.year %>
            <% end %>
            <% if turno.nombrevacuna == "fiebreamarilla" %>
            	  Turno Fiebre Amarilla de <%= User.find(@id).name %> <%=User.find(@id).apellido %> Fecha:<%= turno.fecha.day %> / <%= turno.fecha.month %> /  <%= turno.fecha.year %>
            <% end %>
            <% if turno.nombrevacuna == "gripe" %>
                  Turno Gripe de <%= User.find(@id).name %> <%=User.find(@id).apellido %> Fecha:<%= turno.fecha.day %> / <%= turno.fecha.month %> /  <%= turno.fecha.year %>
            <% end %> 
               <button style="background-color:yellow">
	            <%= link_to "Ver detalles del Turno del Paciente",verdetalleturno_path(turno), class: 'btn btn-info btn-sm' %>
               </button>              
              </p>
           <% end %>
        <h3> Turnos próximos </h3>
        <% Turno.all.where("fecha > ?", Date.today).where("user_id != ?", "nil").order('fecha, hora').each do |turno| %> 
         
            <p>
             <% @id = turno.user_id %>
            <% if turno.nombrevacuna == "covid1" %>
                  Turno Primera dosis COVID-19 de <%= User.find(@id).name %> <%=User.find(@id).apellido %> Fecha:<%= turno.fecha.day %> / <%= turno.fecha.month %> /  <%= turno.fecha.year %>
            <% end %>
            <% if turno.nombrevacuna == "covid2" %>
                  Turno Segunda dosis COVID-19 de <%= User.find(@id).name %> <%=User.find(@id).apellido %> Fecha:<%= turno.fecha.day %> / <%= turno.fecha.month %> /  <%= turno.fecha.year %>
            <% end %>
            <% if turno.nombrevacuna == "fiebreamarilla" %>
            	  Turno Fiebre Amarilla de <%= User.find(@id).name %> <%=User.find(@id).apellido %> Fecha:<%= turno.fecha.day %> / <%= turno.fecha.month %> /  <%= turno.fecha.year %>
            <% end %>
            <% if turno.nombrevacuna == "gripe" %>
                  Turno Gripe de <%= User.find(@id).name %> <%=User.find(@id).apellido %> Fecha:<%= turno.fecha.day %> / <%= turno.fecha.month %> /  <%= turno.fecha.year %>
            <% end %>   
            <button style="background-color:yellow">
	            <%= link_to "Ver detalles del Turno del Paciente",verdetalleturno_path(turno), class: 'btn btn-info btn-sm' %>
               </button>             
            </p>

       <% end %> 

<%= link_to "Atrás", pantallaenfermero_path %>
   

</div>

</body>
</html>

app/views/turnos/historialdeturnospaciente.html.erb
<!DOCTYPE html> 
<html>
<head>
<script type="text/javascript" src="Scripts/jquery-2.1.1.min.js"></script>
<script type="text/javascript" src="Scripts/bootstrap.min.js"></script>
</head>
<body>
<h1> Historial de Turnos </h1> 
<div>
   <% u = User.find(params[:id]) %>
  <h3> Turnos pasados </h3>
           <% Turno.all.where("fecha < ?", Date.today).where(user_id: u.id).order('fecha, hora').each do |turno|%>
              <p>
              <% if turno.nombrevacuna == "covid1" %>
                  Turno Primera dosis COVID-19   
            <% end %>
            <% if turno.nombrevacuna == "covid2" %>
                  Turno Segunda dosis COVID-19 
            <% end %>
            <% if turno.nombrevacuna == "fiebreamarilla" %>
            	  Turno Fiebre Amarilla  
            <% end %>
            <% if turno.nombrevacuna == "gripe" %>
                  Turno Gripe
            <% end %> 
               <button style="background-color:yellow">
	            <%= link_to "Ver detalles del Turno del Paciente",verdetalleturno_path(turno), class: 'btn btn-info btn-sm' %>
               </button>              
              </p>
           <% end %>
        <h3> Turnos del dia </h3>
        <% Turno.all.where(user_id: u.id).where("fecha = ?", Date.today).order('fecha, hora').each do |turno| %> 
            <p>
            <% if turno.nombrevacuna == "covid1" %>
                  Turno Primera dosis COVID-19  
            <% end %>
            <% if turno.nombrevacuna == "covid2" %>
                  Turno Segunda dosis COVID-19 
            <% end %>
            <% if turno.nombrevacuna == "fiebreamarilla" %>
            	  Turno Fiebre Amarilla 
            <% end %>
            <% if turno.nombrevacuna == "gripe" %>
                  Turno Gripe
            <% end %>  
                 <button style="background-color:yellow">
	            <%= link_to "Ver detalles del Turno del Paciente",verdetalleturno_path(turno), class: 'btn btn-info btn-sm' %>
               </button>              
              </p>
             <% end %>
          <h3> Turnos próximos </h3>
            <% Turno.all.where(user_id: u.id).where("fecha > ?", Date.today).order('fecha, hora').each do |turno| %> 
            <p>
            <% if turno.nombrevacuna == "covid1" %>
                  Turno Primera dosis COVID-19  
            <% end %>
            <% if turno.nombrevacuna == "covid2" %>
                  Turno Segunda dosis COVID-19 
            <% end %>
            <% if turno.nombrevacuna == "fiebreamarilla" %>
            	  Turno Fiebre Amarilla 
            <% end %>
            <% if turno.nombrevacuna == "gripe" %>
                  Turno Gripe
            <% end %>  
                 <button style="background-color:yellow">
	            <%= link_to "Ver detalles del Turno del Paciente",verdetalleturno_path(turno), class: 'btn btn-info btn-sm' %>
               </button>              
              </p>  

       <% end %> 


<%= link_to "Atrás", pantallaenfermero_path %>
   

</div>

</body>
</html>

app/views/turnos/listado.html.erb
<!DOCTYPE html> 
<html>
<head>
<script type="text/javascript" src="Scripts/jquery-2.1.1.min.js"></script>
<script type="text/javascript" src="Scripts/bootstrap.min.js"></script>
</head>
<body>
<h1> Turnos del dia <%= Date.today.day %> / <%= Date.today.month %> /  <%= Date.today.year %></h1> 
<div>
<button style="background-color:yellow">
     <%= link_to "Marcar Vacuna Aplicada Sin Turno", aplicadasinturno_path(current_user), class: 'btn btn-info btn-sm' %>
</button>
<% if user_signed_in? and current_user.rol == 2 %>
    <% if @t.any? %>
        <table class = "table">
                <tr>
                <th>Paciente</th>
             
                <th> Hora   </th>
               
                <th> Vacuna </th>
                <th> Asistencia <th>
                <th> Aplicada <th>
                </tr>
            <% @t.order('hora').each do |tur| %>
                <% @u = User.find(tur.user_id) %>
                <tr>
                    
                    <td><%= "#{@u.name} #{@u.apellido}" %></td>
                    <td><%= tur.hora.hour%>:<%= tur.hora.strftime('%M')%></td>
                    <td><% if tur.nombrevacuna == "covid1"%>
                                  Primera Dosis Covid 
                           <% elsif tur.nombrevacuna == "covid2" %>
                                  Segunda Dosis Covid 
                           <% elsif tur.nombrevacuna == "gripe" %>
                                  Gripe
                            <% elsif tur.nombrevacuna == "fiebreamarilla" %>
                                  Fiebre Amarilla      
                            <% end %>
                          </td>
                          <td>
                                <% if (tur.aplicada == true) %> 
                                  <button disabled=true>  <%= link_to "✓"%></button>
    			           <% else %>
	                           <button style="background-color:green">
      				       <%= link_to "✓", asistencia_path(tur.id), class: 'btn btn-info btn-sm' %>
      				    </button>
    			         <% end %>
                          </td>
                           <td>
                           
                           </td>
                           <td><% if ((tur.aplicada == true) or (tur.asistencia == nil or tur.asistencia == false)) %> 
                                  <button disabled=true>  <%= link_to "✓"%></button>
                                  <button disabled=true>  <%= link_to "X"%></button>
      				<% else %>  
                                  <button style="background-color:green">
      				   	 <%= link_to "✓", crearcomprobante_path(tur.id), class: 'btn btn-info btn-sm' %>
      				   </button>
      				   <button style="background-color:red">
      					<%= link_to "X", noaplicada_path(tur.id), class: 'btn btn-info btn-sm' %>
    			           </button>
    			       <% end %>
                      </td>
                          <td>
                           	<button style="background-color:yellow">
	          		   <%= link_to "Ver Información del Paciente", verdatospaciente_path(tur.user_id), class: 'btn btn-info btn-sm' %>
          			</button>   
                           </td>
                           <td>
                    <% if @u.historia.attached? %>
                            <button style="background-color:yellow">
                             <%= link_to "Ver Historia de Vacunación", @u.historia, class: 'btn btn-info btn-sm' %>
                            </button>
                      <% else %>
                            <button disabled=true style="background-color:grey;">
                             <%= link_to "Sin Historia", class: 'btn btn-info btn-sm' %>
                            </button>
                      <% end %>
                      </td>
                           <td>
                           <button style="background-color:yellow">
	                      <%= link_to "Ver Certificados del Paciente",comprobante_index_path(tur.user_id), class: 'btn btn-info btn-sm' %>
                          </button> 
                           </td>
                           <td>
                           <button style="background-color:yellow">
	          <%= link_to "Ver Historial de Turnos del paciente", historialdeturnospaciente_path(tur.user_id), class: 'btn btn-info btn-sm' %>
          </button>  
                           </td>
                           
                           <td>
                              <%= form_for tur do |f| %>
                                <div>
                                   <%= f.label :nota %>
                                   <%= f.text_field :texto%>  
                                   <%= f.submit "Agregar Nota"%>
                                </div>
                              
                                <% end %>
                           </td>
  
                </tr>
            <% end %>
         
        </table>
    <% else %>
        <h1>No hay turnos para este día</h1>
    <% end %>
<% end %>
<%= link_to "Atrás", pantallaenfermero_path %>
</div>
</body>
</html>

app/views/turnos/searchturnos.html.erb
<!DOCTYPE html> 
<html>
<body>
<h1>Resultados de la Búsqueda</h1> 
   <% if not @turnos.any? %>
      <p> No hay coincidencias </p>
   <% end %> 
   <% @turnos.all.order('fecha').each do |turno| %>
       <p>
           <% @id = turno.user_id %>
           
              <% if turno.nombrevacuna == "covid1" %>
                  Turno Primera dosis COVID-19 de <%= User.find(@id).name %> <%=User.find(@id).apellido %> Fecha:<%= turno.fecha.day %> / <%= turno.fecha.month %> /  <%= turno.fecha.year %>
            <% end %>
            <% if turno.nombrevacuna == "covid2" %>
                  Turno Segunda dosis COVID-19 de <%= User.find(@id).name %> <%=User.find(@id).apellido %> Fecha:<%= turno.fecha.day %> / <%= turno.fecha.month %> /  <%= turno.fecha.year %>
            <% end %>
            <% if turno.nombrevacuna == "fiebreamarilla" %>
            	  Turno Fiebre Amarilla de <%= User.find(@id).name %> <%=User.find(@id).apellido %> Fecha:<%= turno.fecha.day %> / <%= turno.fecha.month %> /  <%= turno.fecha.year %>
            <% end %>
            <% if turno.nombrevacuna == "gripe" %>
                  Turno Gripe de <%= User.find(@id).name %> <%=User.find(@id).apellido %> Fecha:<%= turno.fecha.day %> / <%= turno.fecha.month %> /  <%= turno.fecha.year %>
            <% end %> 
               <button style="background-color:yellow">
	            <%= link_to "Ver detalles del Turno del Paciente",verdetalleturno_path(turno), class: 'btn btn-info btn-sm' %>
               </button>              
       </p>
         
    <% end %> 


    
<%= link_to "Atrás", historialdeturnos_path(current_user) %>
   

</div>

</body>
</html>